apiVersion: v1
kind: Service
metadata:
  name: es01
  labels:
    app: es-service
spec:
  type: NodePort
  ports:
    - port: 9200
      name: es-9200
      nodePort: 30292
    - port: 9300
      name: es-9300
  selector:
    app: elasticsearch-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch-tmpl
    spec:
      containers:
      - image: idmefv2prototype/elasticsearch:main
        name: elasticsearch
        env:
        - name: ES_JAVA_OPTS
          value: -Xms4g -Xmx4g
        - name: ELASTIC_PASSWORD
          value: elastic
        ports:
        - containerPort: 9200
          name: es-9200
        - containerPort: 9300
          name: es-9300
        volumeMounts:
          - name: config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
      volumes:
      - name: config
        hostPath:
          path: /mnt/minikube/elasticsearch/config
          type: Directory
