apiVersion: v1
kind: Service
metadata:
  name: gui
  labels:
    app: gui-service
spec:
  type: NodePort
  ports:
    - port: 8000
      name: gui-8000
      targetPort: 80
      nodePort: 30080
  selector:
    app: gui-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  labels:
    app: gui-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gui-tmpl
    spec:
      containers:
      - image: idmefv2prototype/gui:main
        name: gui
        ports:
        - containerPort: 80
          name: gui-80
        volumeMounts:
          - name: config
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
          - name: config
            mountPath: /etc/prewikka/prewikka.conf
            subPath: config/prewikka.conf
          - name: config
            mountPath: /etc/prewikka/conf.d/auth.conf
            subPath: config/auth.conf
          - name: config
            mountPath: /etc/prewikka/conf.d/idmefv2.conf
            subPath: config/idmefv2.conf
          - name: config
            mountPath: /etc/prewikka/conf.d/logs.conf
            subPath: config/logs.conf
          - name: config
            mountPath: /etc/prewikka/menu.yml
            subPath: config/menu.yml
      volumes:
      - name: config
        hostPath:
          path: /mnt/minikube/gui
          type: Directory
