apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  labels:
    app: kafdrop-service
spec:
  type: NodePort
  ports:
    - port: 9201
      name: kafdrop-9201
      nodePort: 30192
  selector:
    app: kafdrop-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    app: kafdrop-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafdrop-tmpl
    spec:
      containers:
      - image: idmefv2prototype/kafdrop:main
        name: kafdrop
        env:
        - name: KAFKA_BROKERCONNECT
          value: "kafka:9092"
        - name: JVM_OPTS
          value: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        - name: CMD_ARGS
          value: "--server.port=9201"
        ports:
        - containerPort: 9201
          name: kafdrop-9201
