apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka-service
spec:
  ports:
    - port: 9092
      name: kafka-9092
    - port: 29092
      name: kafka-29092
    - port: 19092
      name: kafka-19092
    - port: 9999
      name: kafka-9999
  selector:
    app: kafka-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-tmpl
    spec:
      containers:
      - image: idmefv2prototype/kafka:main
        name: kafka
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka:19092,EXTERNAL://kafka:9092,DOCKER://kafka:29092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LOG4J_LOGGERS
          value: "kafka.controller=DEBUG,kafka.producer.async.DefaultEventHandler=DEBUG,state.change.logger=DEBUG"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "9999"
        - name: KAFKA_JMX_HOSTNAME
          value: kafka
        - name: KAFKA_AUTHORIZER_CLASS_NAME
          value: kafka.security.authorizer.AclAuthorizer
        - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
          value: "true"
        - name: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
          value: "false"
        - name: KAFKA_PORT
          value: ""
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        ports:
        - containerPort: 9092
          name: kafka-9092
        - containerPort: 29092
          name: kafka-29092
        - containerPort: 9999
          name: kafka-9999
        - containerPort: 19092
          name: kafka-19092
