apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-service
spec:
  type: NodePort
  ports:
    - port: 8100
      name: nginx-8100
      targetPort: 80
      nodePort: 30081
  selector:
    app: nginx-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-tmpl
    spec:
      containers:
      - image: idmefv2prototype/nginx:main
        name: nginx
        ports:
        - containerPort: 80
          name: nginx-80
        volumeMounts:
          - name: config
            mountPath: /var/www/html/index.html
            subPath: index.html
          - name: config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
      volumes:
      - name: config
        hostPath:
          path: /mnt/minikube/nginx
          type: Directory
