apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-service
spec:
  ports:
    - port: 5432
      name: pg-5432
  selector:
    app: postgres-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-tmpl
    spec:
      containers:
      - image: idmefv2prototype/postgres:main
        name: postgres
        env:
        - name: POSTGRES_DB
          value: prewikka
        - name: POSTGRES_USER
          value: prelude
        - name: POSTGRES_PASSWORD
          value: prelude
        - name: PGDATA
          value: /data/postgres
        ports:
        - containerPort: 5432
          name: pg-5432
