apiVersion: v1
kind: Service
metadata:
  name: zoo
  labels:
    app: zoo-service
spec:
  ports:
    - port: 2181
      name: zoo-2181
  selector:
    app: zoo-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo
  labels:
    app: zoo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zoo-tmpl
    spec:
      containers:
      - image: idmefv2prototype/zoo:main
        name: zoo
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_SERVERS
          value: "zoo:2888:3888"
        ports:
        - containerPort: 2181
          name: zoo-2181
